# Generated by Django 2.2.7 on 2025-07-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herb',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
