# Generated by Django 2.2.7 on 2025-07-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_herb_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
