# Generated by Django 2.2.7 on 2025-07-16 14:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20250713_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='herb',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_herbs', to=settings.AUTH_USER_MODEL),
        ),
    ]
